# Generated by Django 2.2.9 on 2020-01-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='プロジェクト名')),
                ('slug', models.SlugField(unique=True, verbose_name='プロジェクトスラグ')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('overview', models.CharField(max_length=255, verbose_name='概要')),
                ('description', models.TextField()),
                ('release_condition', models.CharField(choices=[('public', '全員に公開'), ('limited', 'LIMITED')], default='limited', max_length=50, verbose_name='閲覧制限')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
