# Generated by Django 2.2.9 on 2020-01-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='overview',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='概要'),
        ),
    ]
