# Generated by Django 2.2.9 on 2020-01-23 05:08

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200123_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='write down in markdown format', null=True, verbose_name='本文'),
        ),
    ]
